### ISSUE TITLE
StringIndexOutBounds when text is less than trim length

### ISSUE THREAD

**Issue by nilskassube** [bravoborja/ReadMoreTextView#10]
If you try to trim by length, and the length of the text is smaller than the limit, you get  

 java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=101
                                                                         at java.lang.String.startEndAndLength(String.java:298)
                                                                         at java.lang.String.getChars(String.java:598)
                                                                         at android.text.TextUtils.getChars(TextUtils.java:81)
                                                                         at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:65)
                                                                         at com.borjabravo.readmoretextview.ReadMoreTextView.updateCollapsedText(ReadMoreTextView.java:137)
                                                                         at com.borjabravo.readmoretextview.ReadMoreTextView.getTrimmedText(ReadMoreTextView.java:115)
                                                                         at com.borjabravo.readmoretextview.ReadMoreTextView.getDisplayableText(ReadMoreTextView.java:92)
                                                                         at com.borjabravo.readmoretextview.ReadMoreTextView.setText(ReadMoreTextView.java:86)

**Comment by JigneshPatel23** [comment]
Same issue. :+1:

**Comment by sandeshlasnapure** [comment]
Still having issue with recycler view, sometime clickable span not adding to text view.
![device-2017-01-24-022331](https://cloud.githubusercontent.com/assets/12455411/22222246/22bd8184-e1dc-11e6-93e4-f4ad64cbece4.png)

**Comment by asywalulfikri** [comment]
i have same problem

**Comment by pudao2010** [comment]
I have same problem,When I use the ReadMoreTextView in RecyclerView,My App will crash,so I abandon it in my App

**Comment by asywalulfikri** [comment]
any body  have resolve it ?

**Comment by ziem** [comment]
Is there any progress on this issue?

**Comment by Robbypatel1357** [comment]
i have same problem if any have solution?

**Comment by Robbypatel1357** [comment]
@sandeshlasnapure  can you show me your for "readmore"?

**Comment by Robbypatel1357** [comment]
using handler may be solve the problem

**Comment by jianjiankedizai** [comment]
this is  a big problem

**Comment by sondevelopervn** [comment]
When I use the ReadMoreTextView in RecyclerView,My App will crash
