### ISSUE TITLE
Can't see the readmore option within recyclerview

### ISSUE THREAD

**Issue by ImdStar-Pranesh** [bravoborja/ReadMoreTextView#22]
Hi,
I tried to implement the ReadMoreTextView but i cant see "**readmore**" option for some items.
![1](https://cloud.githubusercontent.com/assets/25858815/24797371/98d799fc-1bae-11e7-90d4-0ee1b905f86b.png)
And when i clicked on the readmore option of te previous item,i can see it.
Is it an issue or the functionality,Can't figure it out.
![2](https://cloud.githubusercontent.com/assets/25858815/24797411/c90d8e6a-1bae-11e7-88f5-1b362246e62f.png)

**Comment by borjabravo10** [comment]
hi @ImdStar-Pranesh it is an issue. 
At this moment, I don't have time to fix it. A Pull Request is welcome ;)
When I get time, I'll try to see the problem.

**Comment by ImdStar-Pranesh** [comment]
Hi,

 

Thanks for the update.

 

Regards,

Pranesh

**Comment by 287257255** [comment]
so,can i  use it within recyclerViewew?
Does the problem still exist?

**Comment by bravoborja** [comment]
Hi,
What trim mode are you using? With TRIM_MODE_LINES it is possible that the library not working.

Can you try to use the TRIM_MODE_LENGTH? It's working with this?

Thanks for the feedback

**Comment by ahmaadyunus** [comment]
I have same problem. The recyclerview first time set data adapter. Colapse work normally ONLY in first index. When, "read more" clicked readmoretextview in other index colapse normally. And, when the device lock, and open again its work normally in all index automatically. 
Notes: 1 index have 1 readmoretextview and full screen. So, second index not show in first set data to adapter. 
Hopefully fix this soon. 
Thank you

**Comment by palanitringapps** [comment]
Hey, i have the problem in recyclerview, when text.lenght() is 0 then app get crashed, Here i have mention the logs
java.lang.StringIndexOutOfBoundsException: length=0; index=120
        at java.lang.String.substring(String.java:2032)
        at java.lang.String.subSequence(String.java:2079)
        at com.handlrlib.views.ReadMoreTextView.updateCollapsedText(ReadMoreTextView.java:168)
        at com.handlrlib.views.ReadMoreTextView.getTrimmedText(ReadMoreTextView.java:149)
        at com.handlrlib.views.ReadMoreTextView.getDisplayableText(ReadMoreTextView.java:126)

**Comment by m6265m** [comment]
It's working fine with trimModeLength
