### ISSUE TITLE
java.lang.IndexOutOfBoundsException: getChars (0 ... 241) ends beyond length 13...

### ISSUE THREAD

**Issue by scrylove** [bravoborja/ReadMoreTextView#27]
I use ReadMoreTextView in RecyclerView adapter.

-------------this crash log:

java.lang.IndexOutOfBoundsException: getChars (0 ... 241) ends beyond length 13
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1094)
	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:976)
	at android.text.TextUtils.getChars(TextUtils.java:91)
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:65)
	at com.borjabravo.readmoretextview.ReadMoreTextView.updateCollapsedText(ReadMoreTextView.java:137)
	at com.borjabravo.readmoretextview.ReadMoreTextView.getTrimmedText(ReadMoreTextView.java:115)
	at com.borjabravo.readmoretextview.ReadMoreTextView.getDisplayableText(ReadMoreTextView.java:92)
	at com.borjabravo.readmoretextview.ReadMoreTextView.setText(ReadMoreTextView.java:86)
	at com.borjabravo.readmoretextview.ReadMoreTextView.access$200(ReadMoreTextView.java:36)
	at com.borjabravo.readmoretextview.ReadMoreTextView$1.onGlobalLayout(ReadMoreTextView.java:206)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:982)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

-----------and this is my code:

            SpannableString ss = new SpannableString(Html.fromHtml("<font color='#5376a0'> " + 
            userNamesSb + "</font><font color='#666666'> " + action + "：</font>" + msgDesc));
            
            ss.setSpan(noUnderlineSpan, 0, userNamesSb.toString().length(), 
                               Spannable.SPAN_EXCLUSIVE_INCLUSIVE);
            
            readMoreTV.setHighlightColor(getResources().getColor(R.color.colorAccent));
            readMoreTV.setText(ss);

please fix it, thank you!

**Comment by bravoborja** [comment]
Duplicate #19. Close this issue
