### ISSUE TITLE
will not work with text having space,newline or tab

### ISSUE THREAD

**Issue by chikka** [bravoborja/ReadMoreTextView#40]
It is causing crash when tried with text having newline character,tab or space.

**Comment by LoAlex** [comment]
same issue, any fix for this one?

**Comment by LoAlex** [comment]
> @LoAlex you can use [this](https://github.com/chikka/ReadMoreOption) forked library where I have fixed it. I have already generated PR for that library.

no luck, same error.

2018-12-19 16:46:22.762 24696-24696/com.owoh.dev E/XgStat: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
        at com.devs.readmoreoption.ReadMoreOption$1.run(ReadMoreOption.java:90)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
